### ISSUE TITLE
command language: Add support for xonsh

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-ci#21]
The idea would be to support syntax like this one on windows, linux and macosx:

```yml
install:
  commands:
    - xonsh: |
             if 'GIRDER_TOKEN' in ${...}: 
                 girder_client --api-url https://data.kitware.com/api/v1 \
                               --api-key $GIRDER_TOKEN upload \
                               --parent-type collection 
                               --reuse 5817c33a8d777f10f26ee3a7 ./dist/
```
See http://xon.sh for more details

Note also that `xonsh` requires python >= 3.4

**Comment by scopatz** [comment]
Hey @jcfr, Let me know if you need a hand getting anything hooked up! I am happy to help...

**Comment by jcfr** [comment]
Closing.

Since March 2023, the project has been archived and instead we recommend using [cibuildwheel](https://cibuildwheel.readthedocs.io) to support building the project across platforms and CI services.

References:
* https://github.com/scikit-build/scikit-ci/pull/53
