### ISSUE TITLE
yaml parser errors

### ISSUE THREAD

**Issue by mckaymatt** [scikit-build/scikit-ci#35]
My Windows builds keep failing on Python 3.4 because ruamel.yaml==0.15.12 is erroring.  Can you either pin to an earlier version or just pyyaml?  

`ruamel.yaml==0.14.12` will work if you have wheels installed and use `--no-binary`, but `0.15.12` is pinned.

https://ci.appveyor.com/project/mckaymatt/trust-pypi-example/build/57
```
%PYTHON_DIR%\python.exe -m pip install -U pip>=9.0.1 wheel
%PYTHON_DIR%\python.exe -m pip install ruamel.yaml==0.14.12 --no-binary :all:
Collecting ruamel.yaml==0.14.12
  Downloading ruamel.yaml-0.14.12.tar.gz (242kB)
Skipping bdist_wheel for ruamel.yaml, due to binaries being disabled for it.
Installing collected packages: ruamel.yaml
  Running setup.py install for ruamel.yaml: started
    Running setup.py install for ruamel.yaml: finished with status 'done'
Successfully installed ruamel.yaml-0.14.12
%PYTHON_DIR%\python.exe -m pip install -U urllib3[secure] scikit-ci==0.14.0
Collecting urllib3[secure]
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB)
Collecting scikit-ci==0.14.0
  Downloading scikit_ci-0.14.0-py2.py3-none-any.whl
Collecting certifi; extra == "secure" (from urllib3[secure])
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
Collecting ruamel.yaml (from scikit-ci==0.14.0)
  Downloading ruamel.yaml-0.15.12.tar.gz (249kB)
    Complete output from command python setup.py egg_info:
    error in ruamel.yaml setup command: Invalid environment marker: platform_python_implementation=="CPython" and python_version<="2.7"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\appveyor\AppData\Local\Temp\1\pip-build-kod5820l\ruamel.yaml\
```

**Comment by AvdN** [comment]
Python 3.4.6 should not have this issue, 3.4.3 definately does. I haven't checked Python 3.4.4 and 3.4.5 .
The best solution for this is to make sure setuptools is up-to-date, i.e. make the first line
```
%PYTHON_DIR%\python.exe -m pip install -U pip>=9.0.1 setuptools wheel
```

**Comment by mckaymatt** [comment]
Thanks. It does seem to work with setuptools installed and upgraded.

**Comment by AvdN** [comment]
Can you tell me what  version of 3.4 this is?

**Comment by mckaymatt** [comment]
It looks like 3.4.4.

**Comment by AvdN** [comment]
3.4.4 is from December 2015, 3.4.5 is from June 2016 and should be ok, unless they bundled an older setuptools. 
I might look into appveyor once more, and generate binary wheels for Windows for ruamel.yaml and ruamel.ordereddict, then you would not have to compile the modules yourself (but you still would need an up-to-date wheel and setuptools)

**Comment by jcfr** [comment]
Thanks Anthon for your help. :+1

On Jun 24, 2017 3:55 PM, "Anthon van der Neut" <notifications@github.com>
wrote:

3.4.4 is from December 2015, 3.4.5 is from June 2016 and should be ok,
unless they bundled an older setuptools.
I might look into appveyor once more, and generate binary wheels for
Windows for ruamel.yaml and ruamel.ordereddict, then you would not have to
compile the modules yourself (but you still would need an up-to-date wheel
and setuptools)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scikit-build/scikit-ci/issues/35#issuecomment-310862230>,
or mute the thread

**Comment by jcfr** [comment]
Based on the comment, this was addressed.

Also, PR #42  will be integrated shortly and will fix support for ruamel.yaml >= 0.15.52
