### ISSUE TITLE
Support for deploy step

### ISSUE THREAD

**Issue by JoostJM** [scikit-build/scikit-ci#36]
Currently, SciKit-CI has several steps for integrating continuous integration.
However, the deploy step is currently not part of this. Is there a possibility that this step is added in the future? This would greatly help to setup cross-platform continuous deployment to e.g. PyPi.

Related to issue on google groups: https://groups.google.com/forum/#!topic/scikit-build/DxqHIbgDPMA

**Comment by jcfr** [comment]
Closing.

Since March 2023, the project has been archived and instead we recommend using [cibuildwheel](https://cibuildwheel.readthedocs.io) to support building the project across platforms and CI services.

References:
* https://github.com/scikit-build/scikit-ci/pull/53
