### ISSUE TITLE
wordcloud circle ci broken for python>=3.5

### ISSUE THREAD

**Issue by amueller** [scikit-build/scikit-ci#51]
It looks like the wordcloud circle build is broken and it looks related to scikit-ci, I think?
https://github.com/amueller/word_cloud/pull/535

I'm not sure what could cause this.

**Comment by jcfr** [comment]
Closing.

Since March 2023, the project has been archived and instead we recommend using [cibuildwheel](https://cibuildwheel.readthedocs.io) to support building the project across platforms and CI services.
