### ISSUE TITLE
Review how command within a step are combined

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-ci#6]
Currently the command from the specialized section are appended to the common one, we may revisit to have them overwrite instead.

Thanks for @thewtex for pointing this out

**Comment by thewtex** [comment]
@jcfr 

Thanks!

This patch is a reference of your suggested modification from our discussion:

  https://github.com/thewtex/scikit-ci/commit/657ac0c3ba00c7a3865ac02ac5551a517214dbe5

**Comment by jcfr** [comment]
Closing.

Since March 2023, the project has been archived and instead we recommend using [cibuildwheel](https://cibuildwheel.readthedocs.io) to support building the project across platforms and CI services.

References:
* https://github.com/scikit-build/scikit-ci/pull/53
